# Where things are
source              : .
destination         : ./_site
collections_dir     : .
plugins_dir         : _plugins # takes an array of strings and loads plugins in that order
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes
sass:
  sass_dir: _sass
collections:
  posts:
    output          : true

# Plugins
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


# Add themes
remote_theme: pages-themes/cayman@v0.2.0

# Stylesheets 
title: Joseph ASSIGA
description: Discover, share and learn new tricks for techs
