# Where things are
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Add themes
theme: jekyll-theme-cayman

# Stylesheets 
title: Joseph ASSIGA
description: Discover, share and learn new tricks for techs
