project:
  type: website

website:
  title: "."
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/josephassiga
      - icon: twitter
        href: https://twitter.com/assigajoseph
format:
  html:
    theme: cosmo
    css: styles.css



