project:
  type: website

website:
  title: "AI & ML Blogs"
  site-url: https://josephassiga.github.io/
  navbar:
    background: primary
    left: 
      - about.qmd
    right:
      - icon: github
        href: https://github.com/josephassiga
      - icon: twitter
        href: https://twitter.com/assigajoseph
      - icon: linkedin
        href: https://www.linkedin.com/in/josephassiga/
  favicon: images/favicon.ico
  twitter-card: true
  open-graph: true
  page-footer: "Copyright 2024, Joseph Assiga" 
format:
  html:
    theme: cosmo
    css: styles.css



