project:
  type: website

website:
  title: "AI & ML Blogs"
  description: "Illustrated tutorials about large language models, graph neural networks, and convex optimization using Python."
  site-url: https://josephassiga.github.io/
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/josephassiga
      - icon: twitter
        href: https://twitter.com/assigajoseph
  favicon: images/favicon.ico
  twitter-card: true
  open-graph: true
  page-footer: "Copyright 2024, Joseph Assiga" 
format:
  html:
    theme: cosmo
    css: styles.css



