apiVersion: v1
kind: Secret
metadata:
  name: hf-credentials
  namespace: models
type: Opaque
stringData:
  HF_TOKEN: hf_YOUR_ACTUAL_HUGGINGFACE_TOKEN_HERE
  HF_HUB_ENABLE_HF_TRANSFER: "0"          # Overrides the image default "1" to fix permission locks!
  HF_HUB_DISABLE_SYMLINKS_WARNING: "true" # Cleans up OpenShift directory modification errors